// Mocks generated by Mockito 5.0.14 from annotations
// in flutter_todo_app/test/screens/todo_detail_screen_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:flutter_todo_app/models/todo.dart' as _i4;
import 'package:flutter_todo_app/repositories/todo_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [TodoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoRepository extends _i1.Mock implements _i2.TodoRepository {
  MockTodoRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> postTodo(String? title, String? description) =>
      (super.noSuchMethod(Invocation.method(#postTodo, [title, description]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i3.Future<_i4.Todo?> getTodo(int? id) =>
      (super.noSuchMethod(Invocation.method(#getTodo, [id]),
          returnValue: Future<_i4.Todo?>.value()) as _i3.Future<_i4.Todo?>);
  @override
  _i3.Future<List<_i4.Todo>> getTodos() =>
      (super.noSuchMethod(Invocation.method(#getTodos, []),
              returnValue: Future<List<_i4.Todo>>.value(<_i4.Todo>[]))
          as _i3.Future<List<_i4.Todo>>);
  @override
  _i3.Future<void> updateTodo(_i4.Todo? todo) =>
      (super.noSuchMethod(Invocation.method(#updateTodo, [todo]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i3.Future<void> deleteTodo(int? id) =>
      (super.noSuchMethod(Invocation.method(#deleteTodo, [id]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  String toString() => super.toString();
}
